### ISSUE TITLE
Cant access the web interface for streama!

### ISSUE THREAD

**Issue by ali2077** [dularion/streama#162]
Unfortunately for me I cant access the application via http://your-remote-server:8080. its just a blank page but on Tomcat Web Application Manager I've got Message:  	

FAIL - Application at context path / could not be started.

any help?

**Comment by Otnehs** [comment]
try adding /streama to the end.  http://your-remote-server:8080/streama

**Comment by dularion** [comment]
Are you running it via tomcat? if so, is the tomcat running under http://your-remote-server:8080? easy check is if http://your-remote-server:8080/manager leads you to your manager app. 
If you are running with tomcat: do you have a ROOT.war in the webapps folder and did it auto-create the ROOT/ folder next to it?

**Comment by TheJoe49** [comment]
I think he is seeing something like this when he clicks start.
![2w1ja1t](https://cloud.githubusercontent.com/assets/16162727/14296963/2d22c8cc-fb42-11e5-90ba-9de674942d37.png)

**Comment by dularion** [comment]
Please post your stacktrace via http://pastebin.com/

**Comment by dularion** [comment]
would you mind trying out the new simpler setup with grails 3 ? just to see if that works for you ? https://github.com/dularion/streama/releases/tag/v1.0.0

**Comment by markcoker** [comment]
Using new setup 

> java -Dgrails.env=production-no-mysql -jar streama-0.1.war
`Exception in thread "main" java.lang.UnsupportedClassVersionError: streama/Application : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by dularion** [comment]
Are you using windows? Looks like the wrong java version. make sure your java version is 1.7 or higher. Check using `java -version`

**Comment by markcoker** [comment]
Ubuntu 16.04 LTS - OpenJDK 1.7.0_10

**Comment by dularion** [comment]
Ah damn, was hoping for a straight forward solution :/ I'll have to try to recreate the issue on a remote server then. Will get to that soon ish and get back to you.

**Comment by dularion** [comment]
Would you mind trying out the new grails3 beta?

**Comment by ronilsonalves** [comment]
@dularion I have the same problem here, Stream server does not start and have a blank page
![captura de tela 4](https://cloud.githubusercontent.com/assets/8782579/18981217/7e79267a-86b2-11e6-94d4-1cef4a64059c.png)

**Comment by gkiko** [comment]
Closing the issue. Please open a new one if you experience same problem with _grails3_ version of streama.
