### ISSUE TITLE
Cant build ROOT.war and cannot access the web interface 

### ISSUE THREAD

**Issue by TheJoe49** [dularion/streama#163]
I have the same exact problem that ali2077 has, and something close to the one that #114 had. 
When ever I run ./grailsw war ROOT.war -Dgrails.env=productio it seems to finish but right above it it says 1 error. Is  that normal?

**Output** (Just copping the bottom chunk because I could not even reach the top.)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.grails.cli.support.GrailsStarter.rootLoader(GrailsStarter.java:236)
	at org.codehaus.groovy.grails.cli.support.GrailsStarter.main(GrailsStarter.java:264)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.grails.wrapper.GrailsWrapper.main(GrailsWrapper.java:93)

1 error
justin@Ubuntu-Server:~/Desktop/Streama/streama$

**Comment by dularion** [comment]
Unfortunately that isn't enough of a stacktrace.. Can you run it again with the flags --stacktrace --verbose and paste the resulting stacktrace in a pastebin?

**Comment by TheJoe49** [comment]
How would the command look?

**Comment by gkiko** [comment]
If you want to evaluate _streama_ app you can run `docker-compose up` from
project root and avoid grails problem.

google how to use `docker-compose`

**Comment by TheJoe49** [comment]
So after doing a lot of research I was able to find out that I typed something wrong when installing java. But thanks for the help.

**Comment by doobee46** [comment]
I had that error when i was installing mine .make sure you default jdk installed and make sure you setup the JAVA_HOME variable in the /etc/environment.
