### ISSUE TITLE
Error when attempting to view manually-added videos

### ISSUE THREAD

**Issue by asmartin** [dularion/streama#169]
Hello,

I am currently running streama v0.2.0. I manually added a show that is not on The Movie DB and then uploaded an episode to it. This worked - I appear to have been able to successfully upload the video. However, when I go to view it, I get this error:

````
2016-04-30 19:24:08,938 [http-bio-80-exec-11] ERROR errors.GrailsExceptionResolver  - FileNotFoundException occurred when processing request: [GET] /theMovieDb/countNewEpisodesForSeason
https://api.themoviedb.org/3/tv/null/season/2007?api_key=bf3c0b3232cbfa73da393379c15d2688. Stacktrace follows:
java.io.FileNotFoundException: https://api.themoviedb.org/3/tv/null/season/2007?api_key=bf3c0b3232cbfa73da393379c15d2688
        at streama.TheMovieDbController.listNewEpisodesForSeason(TheMovieDbController.groovy:63)
        at streama.TheMovieDbController.countNewEpisodesForSeason(TheMovieDbController.groovy:81)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
        at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:49)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
````

Is this a bug? My understanding is that since this is a manually-added video, no query to The Movie DB should be necessary (since it won't be found there). Please let me know what I can do to help test and fix this, thanks!!

**Comment by asmartin** [comment]
Any updates on this?

**Comment by gkiko** [comment]
Sorry, hadn't time to investigate it

**Comment by asmartin** [comment]
No problem, thanks for the quick reply!

**Comment by gkiko** [comment]
I thought it was another issue 😆 
Will take a look anyways

**Comment by dularion** [comment]
Oh yeah, you're absolutely right, no query to themoviedb should be made. In all honesty, I never intended for that feature to be used when no moviedb api key is added at all. I'll try to take a look at it soon, or have you done anything here already @gikko?

**Comment by asmartin** [comment]
Most of what I've added to the library is on TheMovieDB, but I have a few
things that aren't (which I want to manually add)

**Comment by dularion** [comment]
fixed in https://github.com/dularion/streama/releases/tag/v0.3.2

**Comment by asmartin** [comment]
Confirmed, this is now fixed. Thanks!
