### ISSUE TITLE
v1.0.0 - error 500 when adding TV Show

### ISSUE THREAD

**Issue by gkiko** [dularion/streama#184]
_What I did_: searched for a new TV Show and clicked Save button

_What I expected_: navigate to a new page where I can fetch all episodes for season

_Actual result_: no changes in GUI.

Grails console displayed this error
```
ERROR org.grails.web.errors.GrailsExceptionResolver - NullPointerException occurred when processing request: [POST] /tvShow/save.json
Cannot set property 'properties' on null object. Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:53)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62)
	at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: Cannot set property 'properties' on null object
	at streama.TvShowController.$tt__save(TvShowController.groovy:33)
	at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96)
	at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
	... 6 common frames omitted
```

**Comment by dularion** [comment]
Thanks for your PR!
