### ISSUE TITLE
Invited user gets error 500

### ISSUE THREAD

**Issue by gkiko** [dularion/streama#195]
Steps to reproduce:

1. log in as admin and send invitation
2. open invitation link
3. fill input fields so that they don't match or their length < 6

Result:
```
ERROR org.grails.web.errors.GrailsExceptionResolver - CannotRedirectException occurred when processing request: [POST] /invite/setPassword - parameters:
password: asd
passwordRepeat: asd
uuid: a06ed72b-efe7-4ff8-b994-23d90779814d
Cannot issue a redirect(..) here. A previous call to redirect(..) has already redirected the response.. Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:53)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62)
	at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: grails.web.mapping.mvc.exceptions.CannotRedirectException: Cannot issue a redirect(..) here. A previous call to redirect(..) has already redirected the response.
	at grails.web.mapping.ResponseRedirector.redirect(ResponseRedirector.groovy:66)
	at grails.artefact.controller.support.ResponseRedirector$Trait$Helper.redirect(ResponseRedirector.groovy:120)
	at grails.artefact.Controller$Trait$Helper.redirect(Controller.groovy:241)
	at streama.InviteController.setPassword(InviteController.groovy:24)
	... 6 common frames omitted
```

and user gets `{"message":"Internal server error","error":500}`

**Comment by robsonolivesa** [comment]
I am get this error (Internal Server Error 500) after run java -Dgrails.env=prod -jar streama-1.0.4.war. Is the same error?

**Comment by dularion** [comment]
Possibly.. Can you post the stacktrace? If it's long use paste bin plz

**Comment by gkiko** [comment]
Do same steps reproduce the error?

**Comment by robsonolivesa** [comment]
http://pastebin.com/s3s1FLt7

the steps are in the paste. Thanks

**Comment by dularion** [comment]
This is a different issue. I had the same issue when running it from a different folder than where the .war file resides. But from your pastebin I can see that you do run it from the same directory. 
Which Java version are you using?
