### ISSUE TITLE
Error on statup

### ISSUE THREAD

**Issue by lukesnowden** [dularion/streama#21]
```
MacBook-Pro:$ cd ~/GitHub/streama/
MacBook-Pro:$ ./grailsw run-war
Jul 31, 2015 3:03:57 PM org.codehaus.groovy.runtime.m12n.MetaInfExtensionModule newModule
| Precompiling Assets!.
| Error Error executing script RunWar: java/nio/file/FileSystems (Use --stacktrace to see the full trace)
```

stacktrace:

```
java.lang.NoClassDefFoundError: java/nio/file/FileSystems
	at asset.pipeline.fs.AbstractAssetResolver.isFileMatchingPatterns(AbstractAssetResolver.groovy:214)
	at asset.pipeline.fs.FileSystemAssetResolver$_iterateOverFileSystem_closure4.doCall(FileSystemAssetResolver.groovy:195)
	at asset.pipeline.fs.FileSystemAssetResolver.iterateOverFileSystem(FileSystemAssetResolver.groovy:191)
	at asset.pipeline.fs.FileSystemAssetResolver.scanForFiles(FileSystemAssetResolver.groovy:180)
	at asset.pipeline.fs.FileSystemAssetResolver.scanForFiles(FileSystemAssetResolver.groovy:183)
	at asset.pipeline.fs.AssetResolver$scanForFiles.call(Unknown Source)
	at asset.pipeline.AssetCompiler$_getAllAssets_closure3.doCall(AssetCompiler.groovy:231)
	at asset.pipeline.AssetCompiler.getAllAssets(AssetCompiler.groovy:230)
	at asset.pipeline.AssetCompiler$getAllAssets$1.callCurrent(Unknown Source)
	at asset.pipeline.AssetCompiler.compile(AssetCompiler.groovy:65)
	at asset.pipeline.AssetCompiler$compile.call(Unknown Source)
	at _AssetCompile_groovy$_run_closure2.doCall(_AssetCompile_groovy:78)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at _Events$_run_closure1.doCall(_Events.groovy:5)
	at _GrailsWar$_run_closure2.doCall(_GrailsWar.groovy:43)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at RunWar$_run_closure1.doCall(RunWar.groovy:40)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:381)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy:415)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy)
	at gant.Gant.withBuildListeners(Gant.groovy:427)
	at gant.Gant.this$2$withBuildListeners(Gant.groovy)
	at gant.Gant$this$2$withBuildListeners$0.callCurrent(Unknown Source)
	at gant.Gant.dispatch(Gant.groovy:415)
	at gant.Gant.this$2$dispatch(Gant.groovy)
	at gant.Gant.invokeMethod(Gant.groovy)
	at gant.Gant.executeTargets(Gant.groovy:591)
	at gant.Gant.executeTargets(Gant.groovy:590)
	at org.grails.wrapper.GrailsWrapper.main(GrailsWrapper.java:93)
Caused by: java.lang.ClassNotFoundException: java.nio.file.FileSystems
```

any help much appreciated

**Comment by dularion** [comment]
You seem to be using Java 6, is that correct? You can check by using `echo $JAVA_HOME`

**Comment by lukesnowden** [comment]
It's coming up blank... added 
```
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Home"
```
to `~/.profile` but still blank.. checked the path is correct.

**Comment by dularion** [comment]
I think that link is incorrect.. for me (on mac) it has a /Contents/ inbetween. it looks like this

/Library/Java/JavaVirtualMachines/jdk1.7.0_40.jdk/Contents/Home

**Comment by lukesnowden** [comment]
yup, add `export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home` to `~/.bash_profile` and its running now, thanks.
