### ISSUE TITLE
Edit movie after create

### ISSUE THREAD

**Issue by Rockybb** [dularion/streama#217]
hello! 

I running the beta version. When I have create a movie and I want to edit something, I get at internal server error?
in my linux console, get I this:

```
at grails.plugin.json.builder.JsonOutput.writeMap(JsonOutput.java:460)
        at grails.plugin.json.builder.JsonOutput.writeObject(JsonOutput.java:331
at grails.plugin.json.builder.JsonOutput.writeMap(JsonOutput.java:460)
        at grails.plugin.json.builder.JsonOutput.writeObject(JsonOutput.java:331
at grails.plugin.json.builder.JsonOutput.writeMap(JsonOutput.java:460)
        at grails.plugin.json.builder.JsonOutput.writeObject(JsonOutput.java:331
at grails.plugin.json.builder.JsonOutput.writeMap(JsonOutput.java:460)
        at grails.plugin.json.builder.JsonOutput.writeObject(JsonOutput.java:331
```

Someone know how to fix it?

**Comment by Rockybb** [comment]
but it is only if I have upload some movie file....

**Comment by rayonaboat** [comment]
I am experiencing the same bug. Once I have uploaded the movie, i cannot edit anything at it.

**Comment by gkiko** [comment]
Which branch do you build? And what command do you execute to build the project?

**Comment by rayonaboat** [comment]
Latest release 1.0.6 with mysql setup and changes done to application.yml.
java -Dgrails.env=prod -jar streama-1.0.6.war

**Comment by gkiko** [comment]
This is the error `at streama.MovieController.show(MovieController.groovy:40)`
```
ERROR org.grails.web.errors.GrailsExceptionResolver - StackOverflowError occurred when processing request: [GET] /movie/show.json - parameters:
id: 14
Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:53)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62)
	at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: grails.views.ViewRenderException: Error rendering view: null
	at grails.views.AbstractWritableScript.writeTo(AbstractWritableScript.groovy:33)
	at grails.views.mvc.GenericGroovyTemplateView.renderMergedOutputModel(GenericGroovyTemplateView.groovy:65)
	at grails.views.mvc.renderer.DefaultViewRenderer.render(DefaultViewRenderer.groovy:94)
	at grails.artefact.controller.RestResponder$Trait$Helper.internalRespond(RestResponder.groovy:188)
	at grails.artefact.controller.RestResponder$Trait$Helper.respond(RestResponder.groovy:98)
	at streama.MovieController.show(MovieController.groovy:40)
	at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96)
	at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
	... 6 common frames omitted
Caused by: java.lang.StackOverflowError: null
	at grails.plugin.json.builder.JsonOutput.writeObject(JsonOutput.java:327)
	at grails.plugin.json.builder.JsonOutput.writeMap(JsonOutput.java:460)
	at grails.plugin.json.builder.JsonOutput.writeObject(JsonOutput.java:331)
	at grails.plugin.json.builder.JsonOutput.writeMap(JsonOutput.java:460)
```
