### ISSUE TITLE
Version 1.07 does not start ERROR org.apache.coyote.http11.Http11NioProtocol 

### ISSUE THREAD

**Issue by ManuGithubSteam** [dularion/streama#238]
Hi
I get this after ./streama...1.07,war

INFO streama.Application - Starting Application on diynas with PID 7567 (started by root in /nas/server/streama_server)
DEBUG streama.Application - Running with Spring Boot v1.3.3.RELEASE, Spring v4.2.5.RELEASE
INFO streama.Application - The following profiles are active: production

Configuring Spring Security Core ...
... finished configuring Spring Security Core

ERROR org.apache.coyote.http11.Http11NioProtocol - Failed to start end point associated with ProtocolHandler ["http-nio-8080"]
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:340)
        at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:765)
        at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:473)
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:986)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
        at org.apache.catalina.core.StandardService.addConnector(StandardService.java:239)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.addPreviouslyRemovedConnectors(TomcatEmbeddedServletContainer.java:194)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
        at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:55)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:374)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:363)
        at grails.boot.GrailsApp$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
        at streama.Application.main(Application.groovy:8)
        ... 6 more
Caused by: java.lang.IllegalStateException: Tomcat connector in failed state
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:159)

I have also a nginx server with multiple virtual hosts running and this all runs on ubuntu 16.04.

Any ideas ?

Can i use nginx for this ? I hae a lot of oter stuff runnning with it and would prefer that...

Thanks

**Comment by ManuGithubSteam** [comment]
This can be closed i think. The error does not appear when you install "real" (read ORACLE JDK 8.0)
