### ISSUE TITLE
Error Failed to instantiate SLF4J LoggerFactory on startup

### ISSUE THREAD

**Issue by nicolasbd** [dularion/streama#240]
Hi,
I just installed streama on my mac in order to test it, I've defined JAVA_HOME and Mysql database, but when I try to run `./grailsw run-war` I get this error : 

```$ ./grailsw run-war
12 janv. 2017 15:59:47 org.codehaus.groovy.runtime.m12n.MetaInfExtensionModule newModule
| Loading Grails 2.4.4
| Error SLF4J: Class path contains multiple SLF4J bindings.
| Error SLF4J: Found binding in [jar:file:/Users/nbarthedejean/Code/lib/slf4j-1.7.21/slf4j-simple-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
| Error SLF4J: Found binding in [jar:file:/Users/nbarthedejean/.grails/wrapper/2.4.4/grails-2.4.4/lib/org.slf4j/slf4j-simple/jars/slf4j-simple-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
| Error SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
| Error Failed to instantiate SLF4J LoggerFactory
| Error Reported exception:
| Error java.lang.NoClassDefFoundError: org/slf4j/spi/LoggerFactoryBinder
| Error 	at java.lang.ClassLoader.defineClass1(Native Method)
| Error 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
| Error 	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
| Error 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
| Error 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
| Error 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
| Error 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
| Error 	at java.security.AccessController.doPrivileged(Native Method)
| Error 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
| Error 	at org.codehaus.groovy.tools.RootLoader.oldFindClass(RootLoader.java:171)
| Error 	at org.codehaus.groovy.tools.RootLoader.loadClass(RootLoader.java:143)
| Error 	at org.codehaus.groovy.grails.cli.support.GrailsRootLoader.loadClass(GrailsRootLoader.java:51)
| Error 	at java.lang.ClassLoader.loadClass(ClassLoader.java:295)
| Error 	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:655)
| Error 	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:765)
| Error 	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:753)
| Error 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:128)
| Error 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:107)
| Error 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:295)
| Error 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
| Error 	at org.eclipse.sisu.inject.Logs$SLF4JSink.<clinit>(Logs.java:376)
| Error 	at org.eclipse.sisu.inject.Logs.<clinit>(Logs.java:54)
| Error 	at org.eclipse.sisu.inject.DefaultBeanLocator.add(DefaultBeanLocator.java:85)
| Error 	at org.eclipse.sisu.inject.DefaultBeanLocator.staticAutoPublish(DefaultBeanLocator.java:151)
| Error 	at org.eclipse.sisu.inject.DefaultBeanLocator.autoPublish(DefaultBeanLocator.java:144)
| Error 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
| Error 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
| Error 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
| Error 	at java.lang.reflect.Method.invoke(Method.java:597)
| Error 	at com.google.inject.internal.SingleMethodInjector$1.invoke(SingleMethodInjector.java:72)
| Error 	at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:91)
| Error 	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:118)
| Error 	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:80)
| Error 	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:76)
| Error 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1011)
| Error 	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:76)
| Error 	at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:153)
| Error 	at com.google.inject.internal.Initializer.injectAll(Initializer.java:96)
| Error 	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:174)
| Error 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
| Error 	at com.google.inject.Guice.createInjector(Guice.java:94)
| Error 	at com.google.inject.Guice.createInjector(Guice.java:71)
| Error 	at com.google.inject.Guice.createInjector(Guice.java:61)
| Error 	at org.codehaus.plexus.DefaultPlexusContainer.addPlexusInjector(DefaultPlexusContainer.java:477)
| Error 	at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:203)
| Error 	at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:167)
| Error 	at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:161)
| Error 	at org.codehaus.groovy.grails.resolve.maven.aether.AetherDependencyManager.<init>(AetherDependencyManager.groovy:159)
| Error 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
| Error 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
| Error 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
| Error 	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
| Error 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
| Error 	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:71)
| Error 	at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1709)
| Error 	at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1526)
| Error 	at groovy.lang.ExpandoMetaClass.invokeConstructor(ExpandoMetaClass.java:675)
| Error 	at org.codehaus.groovy.runtime.InvokerHelper.invokeConstructorOf(InvokerHelper.java:932)
| Error 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.newInstance(DefaultGroovyMethods.java:12633)
| Error 	at org.codehaus.groovy.grails.resolve.DependencyManagerConfigurer.loadAetherDependencyManager(DependencyManagerConfigurer.groovy:76)
| Error 	at org.codehaus.groovy.grails.resolve.DependencyManagerConfigurer.configureAether(DependencyManagerConfigurer.groovy:48)
| Error 	at grails.util.BuildSettings.configureDependencyManager(BuildSettings.groovy:1280)
| Error 	at grails.util.BuildSettings.postLoadConfig(BuildSettings.groovy:1220)
| Error 	at grails.util.BuildSettings.loadConfig(BuildSettings.groovy:1116)
| Error 	at grails.util.BuildSettings.loadConfig(BuildSettings.groovy:1088)
| Error 	at grails.util.BuildSettings.loadConfig(BuildSettings.groovy)
| Error 	at grails.util.BuildSettings.loadConfig(BuildSettings.groovy:1074)
| Error 	at grails.util.BuildSettings.loadConfig(BuildSettings.groovy)
| Error 	at grails.util.BuildSettings$loadConfig$0.callCurrent(Unknown Source)
| Error 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
| Error 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
| Error 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
| Error 	at grails.util.BuildSettings.loadConfig(BuildSettings.groovy:1054)
| Error 	at org.codehaus.groovy.grails.cli.GrailsScriptRunner.loadConfigEnvironment(GrailsScriptRunner.java:250)
| Error 	at org.codehaus.groovy.grails.cli.GrailsScriptRunner.executeCommand(GrailsScriptRunner.java:359)
| Error 	at org.codehaus.groovy.grails.cli.GrailsScriptRunner.main(GrailsScriptRunner.java:226)
| Error 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
| Error 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
| Error 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
| Error 	at java.lang.reflect.Method.invoke(Method.java:597)
| Error 	at org.codehaus.groovy.grails.cli.support.GrailsStarter.rootLoader(GrailsStarter.java:236)
| Error 	at org.codehaus.groovy.grails.cli.support.GrailsStarter.main(GrailsStarter.java:264)
| Error 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
| Error 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
| Error 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
| Error 	at java.lang.reflect.Method.invoke(Method.java:597)
| Error 	at org.grails.wrapper.GrailsWrapper.main(GrailsWrapper.java:93)
| Error Caused by: java.lang.ClassNotFoundException: org.slf4j.spi.LoggerFactoryBinder
| Error 	at org.codehaus.groovy.tools.RootLoader.findClass(RootLoader.java:175)
| Error 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
| Error 	at org.codehaus.groovy.tools.RootLoader.loadClass(RootLoader.java:147)
| Error 	at org.codehaus.groovy.grails.cli.support.GrailsRootLoader.loadClass(GrailsRootLoader.java:51)
| Error 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
| Error 	... 87 more
| Configuring classpath
| Error Error executing script RunWar: null (Use --stacktrace to see the full trace)```

**Comment by dularion** [comment]
Can you try with v1.0.8?
reopen pls if the problem persists

**Comment by nicolasbd** [comment]
Thanks for your answer,
still have the error, but it seems to "work" with `sudo`, although I run into another error (saw it in another ticket but my JAVA_HOME is actually set) : 

```
$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/
$ sudo ./grailsw run-war
16 janv. 2017 10:59:21 org.codehaus.groovy.runtime.m12n.MetaInfExtensionModule newModule
| Precompiling Assets!.
| Error Error executing script RunWar: java/nio/file/FileSystems (Use --stacktrace to see the full trace)
```

**Comment by dularion** [comment]
why not try 1.0.8?

**Comment by dularion** [comment]
setup is much easier. see here https://github.com/dularion/streama/wiki/BETA--Streama-v1

**Comment by nicolasbd** [comment]
oh my bad, I thought a `git pull` would be enough, cause I've seen a `1.0.8` in the diff, but I'll download it, thanks
