### ISSUE TITLE
Erro na instalação

### ISSUE THREAD

**Issue by Nilbertocs** [dularion/streama#422]
```
root@vmi134614:~# ./streama-1.0.21.war
Exception in thread "main" java.lang.UnsupportedClassVersionError: streama/Application : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:61)
```

Como resolvo isso?

**Comment by Jeronimo95** [comment]
Update to Java 8

**Comment by Nilbertocs** [comment]
Can you send me the command?

**Comment by Jeronimo95** [comment]
What operating system are you using?

**Comment by Nilbertocs** [comment]
Ubuntu 14.04

**Comment by Jeronimo95** [comment]
`sudo apt-get install openjdk-8-jre`

**Comment by Nilbertocs** [comment]
E: Unable to locate package openjdk-8-jre

**Comment by Jeronimo95** [comment]
Try this

```
sudo add-apt-repository ppa:openjdk-r/ppa
sudo apt-get update
sudo apt-get install openjdk-8-jdk
```

**Comment by Nilbertocs** [comment]
It installed but gave the same error, I executed java -version and it continues to 7 ...
I will format the vps to remove conflicts to the maximum and try again

**Comment by Jeronimo95** [comment]
You should be able to use `sudo update-alternatives --config java` to set default java

**Comment by Nilbertocs** [comment]
It worked, it's starting, let's see if it's going to work out

**Comment by Nilbertocs** [comment]
Thanks a lot for the help! Working 100%

**Comment by Nilbertocs** [comment]
Can you tell me if you have any apps compatible with it?
