### ISSUE TITLE
Install Hangs after configuring Security Core

### ISSUE THREAD

**Issue by opolanco23** [dularion/streama#426]
Not sure what could be causing this issue. I am trying to provide as much info as I can.

Digital Ocean VPS 2GB/40GB Ubuntu 16.04.3 x64
Using embedded database version v1.1.0

I got the app to work and even uploaded a few episodes but the script kept crashing because of the 1GB I initially set then I resized and changed to 2GB now the app hangs with no errors after configuring the Security Core.

I've waited up to an hour but it never passes this point.

Any Ideas?

```
root@streama:~# ./streama.war
INFO streama.Application - Starting Application on streama with PID 1846 (started by root in /root)
DEBUG streama.Application - Running with Spring Boot v1.3.8.RELEASE, Spring v4.2.8.RELEASE
INFO streama.Application - The following profiles are active: production
ERROR grails.boot.config.tools.ClassPathScanner - The application defines a Groovy source using the default package. Please move all Groovy sources into a package.

Configuring Spring Security Core ...
... finished configuring Spring Security Core
```

**Comment by dularion** [comment]
try using mysql, does that change anything?

**Comment by jacklenox** [comment]
This is happening to me too.

Also on DigitalOcean VPS 4GB/20GB Ubuntu 16.04.3 x64.

I'll try MySQL.

**Comment by jacklenox** [comment]
I can confirm the same thing happens with MySQL:

```
INFO streama.Application - Starting Application on ubuntu-512mb-lon1-01 with PID 11926 (started by root in /var/www/streama)
DEBUG streama.Application - Running with Spring Boot v1.3.8.RELEASE, Spring v4.2.8.RELEASE
INFO streama.Application - The following profiles are active: production
ERROR grails.boot.config.tools.ClassPathScanner - The application defines a Groovy source using the default package. Please move all Groovy sources into a package.

Configuring Spring Security Core ...
... finished configuring Spring Security Core
```

**Comment by jacklenox** [comment]
Sorry, actually more here. With MySQL enabled it carried on beyond the above with a new error (and lots of output):

```
ERROR org.apache.coyote.http11.Http11NioProtocol - Failed to start end point associated with ProtocolHandler ["http-nio-8
080"]
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:351)
        at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:763)
        at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:491)
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:986)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.StandardService.addConnector(StandardService.java:239)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.addPreviouslyRemovedConnectors
(TomcatEmbeddedServletContainer.java:194)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletCon
tainer.java:151)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(Embedded
WebApplicationContext.java:293)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationCo
ntext.java:141)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.
java:118)
... (abbreviating for sanity)
Caused by: java.lang.IllegalStateException: Tomcat connector in failed state
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletCon
tainer.java:159)
        ... 23 common frames omitted
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:61)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
        ... 3 more
Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat s
ervlet container
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletCon
tainer.java:165)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(Embedded
WebApplicationContext.java:293)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationCo
ntext.java:141)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.
java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
        at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:55)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:374)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:363)
        at grails.boot.GrailsApp$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
        at streama.Application.main(Application.groovy:8)
        ... 8 more
Caused by: java.lang.IllegalStateException: Tomcat connector in failed state
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletCon
tainer.java:159)
        ... 23 more
```

That's the full beginning and end. Let me know if any more output will help.

**Comment by dularion** [comment]
the port is in use. that should mean that you didnt kill the application properly or that something else is using port 8080

**Comment by jacklenox** [comment]
Sorry, I realised that after I typed it! I have something running on 8080. :man_facepalming:

Currently now appears to be working on 8008. :smile:
