### ISSUE TITLE
Logo personalizado

### ISSUE THREAD

**Issue by Guima001** [dularion/streama#472]
Ola, 
Porque ao adicionar uma logo personalizada me apresenta esta mensagem? eu configurei algo errado?
Obrigado!

![image](https://user-images.githubusercontent.com/33711230/32875301-62fc5dca-ca7e-11e7-98e4-076bb737ac9c.png)

**Comment by Jeronimo95** [comment]
Please post the error log from the server console.

**Comment by Guima001** [comment]
Olá, seria isto? sou meio leito no assunto, desculpe se é o arquivo incorreto, poderia me ajudar?

Nov 16 06:25:03 Daenerys-srv rsyslogd: [origin software="rsyslogd" swVersion="8.16.0" x-pid="692" x-info="http://www.rsyslog.com"] rsyslogd was HUPed
Nov 16 06:35:01 Daenerys-srv CRON[6427]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 06:45:01 Daenerys-srv CRON[6435]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 06:55:01 Daenerys-srv CRON[6443]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 07:05:01 Daenerys-srv CRON[6446]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 07:15:01 Daenerys-srv CRON[6454]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 07:17:01 Daenerys-srv CRON[6457]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Nov 16 07:25:01 Daenerys-srv CRON[6464]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 07:35:01 Daenerys-srv CRON[6470]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 07:45:01 Daenerys-srv CRON[6478]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 07:55:01 Daenerys-srv CRON[6486]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 08:05:01 Daenerys-srv CRON[6491]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 08:15:01 Daenerys-srv CRON[6498]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 08:17:01 Daenerys-srv CRON[6501]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Nov 16 08:25:01 Daenerys-srv CRON[6508]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 08:35:01 Daenerys-srv CRON[6513]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 08:45:01 Daenerys-srv CRON[6520]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 08:55:01 Daenerys-srv CRON[6528]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 09:05:01 Daenerys-srv CRON[6533]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 09:15:01 Daenerys-srv CRON[6542]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 09:17:01 Daenerys-srv CRON[6545]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Nov 16 09:25:01 Daenerys-srv CRON[6552]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 09:35:01 Daenerys-srv CRON[6557]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 09:45:01 Daenerys-srv CRON[6565]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 09:55:01 Daenerys-srv CRON[6573]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 10:05:01 Daenerys-srv CRON[6578]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 10:15:01 Daenerys-srv CRON[6586]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 10:17:01 Daenerys-srv CRON[6589]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Nov 16 10:25:01 Daenerys-srv CRON[6595]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 10:35:01 Daenerys-srv CRON[6600]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 10:45:01 Daenerys-srv CRON[6607]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 10:55:01 Daenerys-srv CRON[6615]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 11:05:01 Daenerys-srv CRON[6620]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 11:08:01 Daenerys-srv CRON[6626]: (root) CMD (   test -x /etc/cron.daily/popularity-contest && /etc/cron.daily/popularity-contest --crond)
Nov 16 11:15:01 Daenerys-srv CRON[6630]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 11:17:01 Daenerys-srv CRON[6634]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Nov 16 11:25:01 Daenerys-srv CRON[6640]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 11:35:01 Daenerys-srv CRON[6645]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 11:38:29 Daenerys-srv systemd-networkd[425]: wlp3s0: DHCPv6 address 2804:14c:7b82:8b0a::1/128 timeout preferred 72000 valid 86400
Nov 16 11:45:01 Daenerys-srv CRON[6652]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 11:55:01 Daenerys-srv CRON[6659]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 12:05:01 Daenerys-srv CRON[6663]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 12:15:01 Daenerys-srv CRON[6671]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 12:17:01 Daenerys-srv CRON[6675]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Nov 16 12:25:01 Daenerys-srv CRON[6683]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 12:35:01 Daenerys-srv CRON[6689]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 12:35:22 Daenerys-srv systemd[1]: Created slice User Slice of mrcrow.
Nov 16 12:35:22 Daenerys-srv systemd[1]: Starting User Manager for UID 1000...
Nov 16 12:35:22 Daenerys-srv systemd[1]: Started Session 88 of user mrcrow.
Nov 16 12:35:22 Daenerys-srv systemd[6693]: Starting D-Bus User Message Bus Socket.
Nov 16 12:35:22 Daenerys-srv systemd[6693]: Reached target Paths.
Nov 16 12:35:22 Daenerys-srv systemd[6693]: Reached target Timers.
Nov 16 12:35:22 Daenerys-srv systemd[6693]: Listening on D-Bus User Message Bus Socket.
Nov 16 12:35:22 Daenerys-srv systemd[6693]: Reached target Sockets.
Nov 16 12:35:22 Daenerys-srv systemd[6693]: Reached target Basic System.
Nov 16 12:35:22 Daenerys-srv systemd[6693]: Reached target Default.
Nov 16 12:35:22 Daenerys-srv systemd[6693]: Startup finished in 64ms.
Nov 16 12:35:22 Daenerys-srv systemd[1]: Started User Manager for UID 1000.
Nov 16 12:39:03 Daenerys-srv systemd[1]: Stopping User Manager for UID 1000...
Nov 16 12:39:03 Daenerys-srv systemd[6693]: Stopped target Default.
Nov 16 12:39:03 Daenerys-srv systemd[6693]: Stopped target Basic System.
Nov 16 12:39:03 Daenerys-srv systemd[6693]: Stopped target Timers.
Nov 16 12:39:03 Daenerys-srv systemd[6693]: Stopped target Sockets.
Nov 16 12:39:03 Daenerys-srv systemd[6693]: Stopped target Paths.
Nov 16 12:39:03 Daenerys-srv systemd[6693]: Closed D-Bus User Message Bus Socket.
Nov 16 12:39:03 Daenerys-srv systemd[6693]: Reached target Shutdown.
Nov 16 12:39:03 Daenerys-srv systemd[6693]: Starting Exit the Session...
Nov 16 12:39:03 Daenerys-srv systemd[6693]: Received SIGRTMIN+24 from PID 6806 (kill).
Nov 16 12:39:03 Daenerys-srv systemd[1]: Stopped User Manager for UID 1000.
Nov 16 12:39:03 Daenerys-srv systemd[1]: Removed slice User Slice of mrcrow.
Nov 16 12:39:15 Daenerys-srv kernel: [37989.953858] ICMPv6: NA: someone advertises our address 2804:014c:7b82:8b0a:0000:0000:0000:0001 on wlp3s0!
Nov 16 12:41:14 Daenerys-srv systemd[1]: Created slice User Slice of mrcrow.
Nov 16 12:41:14 Daenerys-srv systemd[1]: Starting User Manager for UID 1000...
Nov 16 12:41:15 Daenerys-srv systemd[1]: Started Session 90 of user mrcrow.
Nov 16 12:41:15 Daenerys-srv systemd[6810]: Reached target Timers.
Nov 16 12:41:15 Daenerys-srv systemd[6810]: Starting D-Bus User Message Bus Socket.
Nov 16 12:41:15 Daenerys-srv systemd[6810]: Reached target Paths.
Nov 16 12:41:15 Daenerys-srv systemd[6810]: Listening on D-Bus User Message Bus Socket.
Nov 16 12:41:15 Daenerys-srv systemd[6810]: Reached target Sockets.
Nov 16 12:41:15 Daenerys-srv systemd[6810]: Reached target Basic System.
Nov 16 12:41:15 Daenerys-srv systemd[6810]: Reached target Default.
Nov 16 12:41:15 Daenerys-srv systemd[6810]: Startup finished in 63ms.
Nov 16 12:41:15 Daenerys-srv systemd[1]: Started User Manager for UID 1000.
Nov 16 12:45:01 Daenerys-srv CRON[6873]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 12:45:18 Daenerys-srv Streama[5212]: WARN grails.app.services.streama.TheMovieDbService - could not load genres this time, api.themoviedb.org
Nov 16 12:45:18 Daenerys-srv Streama[5212]: WARN grails.app.services.streama.TheMovieDbService - could not load genres this time, api.themoviedb.org
Nov 16 12:55:01 Daenerys-srv CRON[6881]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 16 12:58:21 Daenerys-srv systemd[1]: Started Session 94 of user mrcrow.
Nov 16 13:00:05 Daenerys-srv systemd[1]: Started Session 95 of user mrcrow.
Nov 16 13:00:53 Daenerys-srv systemd-timesyncd[419]: Timed out waiting for reply from [2001:67c:1560:8003::c8]:123 (ntp.ubuntu.com).
Nov 16 13:01:03 Daenerys-srv systemd-timesyncd[419]: Timed out waiting for reply from [2001:67c:1560:8003::c7]:123 (ntp.ubuntu.com).

**Comment by mazzucato** [comment]
cara... faz assim

(isso é pra se c tiver executando via linha de comando claro)
./streama-[versão_que_c_ta_usando].war > log.txt

e depois c pega tenta por o logo se n der c pega o resultao do arquivo e coloca pro pastebin e manda o link aqui

**Comment by Guima001** [comment]
https://pastebin.com/ce78xrRk

**Comment by Jeronimo95** [comment]
Is that the everything in the log.txt file? It looks like that's only the end of it. 
Please provide the log (via the method mazzucato shows) from when the server starts until after the issue has happened.

**Comment by bodems** [comment]
I have the same issue with v1.3.1_beta https://pastebin.com/UKEzpyEu

**Comment by dularion** [comment]
Hi, in your log @bodems  i can see this line over and over: 
`Caused by: java.net.UnknownHostException: streama_EN: hostname nor servname provided, or not known` did you customize the war with **streama_EN** anywhere?

**Comment by bodems** [comment]
No, I haven't custimized the .war. streama_EN is the hostname of my FreeBSD jail streama is running in.

**Comment by Jeronimo95** [comment]
I can reproduce on v1.3.2. `No signature of method: ch.qos.logback.classic.Logger.debug()` like issue #471.

```
ERROR org.grails.web.errors.GrailsExceptionResolver - MissingMethodException occurred when processing request: [POST] /file/upload.json
No signature of method: ch.qos.logback.classic.Logger.debug() is applicable for argument types: (streama.File) values: [streama.File : 1]
Possible solutions: debug(java.lang.String), debug(java.lang.String, [Ljava.lang.Object;), debug(java.lang.String, java.lang.Object), debug(java.lang.String, java                                                                           .lang.Throwable), debug(org.slf4j.Marker, java.lang.String), debug(java.lang.String, java.lang.Object, java.lang.Object). Stacktrace follows:
groovy.lang.MissingMethodException: No signature of method: ch.qos.logback.classic.Logger.debug() is applicable for argument types: (streama.File) values: [stream                                                                           a.File : 1]
Possible solutions: debug(java.lang.String), debug(java.lang.String, [Ljava.lang.Object;), debug(java.lang.String, java.lang.Object), debug(java.lang.String, java                                                                           .lang.Throwable), debug(org.slf4j.Marker, java.lang.String), debug(java.lang.String, java.lang.Object, java.lang.Object)
        at streama.UploadService.$tt__upload(UploadService.groovy:55)
        at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
        at streama.FileController.upload(FileController.groovy:201)
        at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:222)
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:187)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:53)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by bodems** [comment]
Works, thanks!
