### ISSUE TITLE
Error on movie upload complete

### ISSUE THREAD

**Issue by Serubin** [dularion/streama#55]
Every so often when uploading movies the following error occurs after hit 100%

```
application-809a66db8e20ffd32c7effd6245327f9.js:357 XHR finished loading: GET "http://titan.serubin.net:8080/movie/show.json?id=6".a @ application-809a66db8e20ffd32c7effd6245327f9.js:357n @ application-809a66db8e20ffd32c7effd6245327f9.js:353$get.r @ application-809a66db8e20ffd32c7effd6245327f9.js:350(anonymous function) @ application-809a66db8e20ffd32c7effd6245327f9.js:385$get.n.$eval @ application-809a66db8e20ffd32c7effd6245327f9.js:400$get.n.$digest @ application-809a66db8e20ffd32c7effd6245327f9.js:397$get.n.$apply @ application-809a66db8e20ffd32c7effd6245327f9.js:401r @ application-809a66db8e20ffd32c7effd6245327f9.js:351H @ application-809a66db8e20ffd32c7effd6245327f9.js:355q.onload @ application-809a66db8e20ffd32c7effd6245327f9.js:356

application-809a66db8e20ffd32c7effd6245327f9.js:357 POST http://titan.serubin.net:8080/video/uploadFile.json?id=6 500 (Internal Server Error)a @ application-809a66db8e20ffd32c7effd6245327f9.js:357n @ application-809a66db8e20ffd32c7effd6245327f9.js:353$get.r @ application-809a66db8e20ffd32c7effd6245327f9.js:350(anonymous function) @ application-809a66db8e20ffd32c7effd6245327f9.js:385$get.n.$eval @ application-809a66db8e20ffd32c7effd6245327f9.js:400$get.n.$digest @ application-809a66db8e20ffd32c7effd6245327f9.js:397$get.n.$apply @ application-809a66db8e20ffd32c7effd6245327f9.js:401(anonymous function) @ application-809a66db8e20ffd32c7effd6245327f9.js:415l @ application-809a66db8e20ffd32c7effd6245327f9.js:305(anonymous function) @ application-809a66db8e20ffd32c7effd6245327f9.js:308

application-809a66db8e20ffd32c7effd6245327f9.js:357 XHR finished loading: POST "http://titan.serubin.net:8080/video/uploadFile.json?id=6".a @ application-809a66db8e20ffd32c7effd6245327f9.js:357n @ application-809a66db8e20ffd32c7effd6245327f9.js:353$get.r @ application-809a66db8e20ffd32c7effd6245327f9.js:350(anonymous function) @ application-809a66db8e20ffd32c7effd6245327f9.js:385$get.n.$eval @ application-809a66db8e20ffd32c7effd6245327f9.js:400$get.n.$digest @ application-809a66db8e20ffd32c7effd6245327f9.js:397$get.n.$apply @ application-809a66db8e20ffd32c7effd6245327f9.js:401(anonymous function) @ application-809a66db8e20ffd32c7effd6245327f9.js:415l @ application-809a66db8e20ffd32c7effd6245327f9.js:305(anonymous function) @ application-809a66db8e20ffd32c7effd6245327f9.js:308

application-809a66db8e20ffd32c7effd6245327f9.js:1051  err ["<!DOCTYPE html>↵<html ng-app="streamaApp" lang="en…has occurred</li>↵			</ul>↵		↵	↵	</body>↵</html>↵", 500, function, Object]
```

I've been posting a lot of issues lately and I just wanted to mention how awesome this project of yours is! Keep up the great work

**Comment by dularion** [comment]
It seems to be referring to a 500 error on the server. do you see any in the logs?

**Comment by Serubin** [comment]
Potentially this.
```
2015-08-02 11:46:53,949 [http-bio-8080-exec-5] ERROR streama.FileController  - catch for outputStream exception
```

**Comment by dularion** [comment]
Ah yep. Could you try commenting out the try-catch wrapper around the response function? 
For me these are lines 64, 73, 74, 75. That way you you will get the real error.

**Comment by Serubin** [comment]
Which file?

**Comment by dularion** [comment]
oh, haha. grails-app/controllers/FileController.groovy

**Comment by Serubin** [comment]
So somewhat unrelated: when playing a video, removing that try/catch has created this error: 
```
2015-08-02 12:56:02,888 [http-bio-8080-exec-4] ERROR errors.GrailsExceptionResolver  - IllegalStateException occurred when processing request: [GET] /file/serve/836cabf98f7ec7df8298dfe7236de73b8d8c065066d7fa01c4edf97eb3f9db03.mp4
getOutputStream() has already been called for this response. Stacktrace follows:
org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: getOutputStream() has already been called for this response
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
        at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:49)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: getOutputStream() has already been called for this response
        at java.io.FilterWriter.flush(FilterWriter.java:100)
        ... 8 more
```
Still waiting on the upload errors

**Comment by dularion** [comment]
yep, its cosmetic. thats why the try-catch is there. wanna get rid of it for real soon, but for now thats why the try-catch is there

**Comment by Serubin** [comment]
Looks like that was the wrong error then. Where else could I find the logs for the server errors? I tried catalina.out

**Comment by dularion** [comment]
catalina.out is the only relevant one. Also, I totally mixed up this issue with the other one you posted. So lets recap: You upload a file, in the frontend it shows you the blue overlay counting up to 100%. When it gets to 100% you get the error. does it then also disappear and the file was added? And at this point, you should not have the outputstream error, if anything, it should be something else. Something in UploadService.groovy.

**Comment by Serubin** [comment]
Once I it gets to 100% it errors in the console. Nothing ends up being uploaded and the 100% doesn't go away, the website shows that there is still no file uploaded.

**Comment by dularion** [comment]
nothing in the catalina either?

**Comment by Serubin** [comment]
Nope. I think the file does get uploaded but the server returns back with the 500 error so it doesn't know how to display it (it gets a html 500 page back which it doesn't seem to like)

**Comment by dularion** [comment]
hmmm.. this is so strange. What is your setup? how do you run the application? what operating system is it running on?

**Comment by Serubin** [comment]
It's Debian 8, it's running on tomcat 7. There's plenty of storage and no disk issues. 

To set it up I build the war and then place it in the tomcat folder specified in the setup instructions.

**Comment by dularion** [comment]
could you paste a ls -la for the upload directory so that I can see the permissions?

**Comment by dularion** [comment]
and: did the application create a subfolder called "upload" inside of the specified directory?

**Comment by Serubin** [comment]
To answer all your questions:

```
seru@titan:/home/streama/data$ ll
total 4.0K
drwxr-xr-x 2 tomcat7 tomcat7 4.0K Aug  2 11:14 upload
seru@titan:/home/streama/data$ cd upload/
seru@titan:/home/streama/data/upload$ ll
total 5.5G
-rw-r--r-- 1 tomcat7 tomcat7 1.5G Aug  2 01:57 adc25540263874d428cb632146eebe39a8e325a155594f7e93512d2968f2c402.mp4
-rw-r--r-- 1 tomcat7 tomcat7 1.1G Aug  2 11:14 9db73c544733e7728a3fd942481c44fad941861e3f888612bf6786b75bfe00bc.mp4
-rw-r--r-- 1 tomcat7 tomcat7 1.5G Aug  2 01:25 836cabf98f7ec7df8298dfe7236de73b8d8c065066d7fa01c4edf97eb3f9db03.mp4
-rw-r--r-- 1 tomcat7 tomcat7 1.5G Aug  2 01:01 3f38b7cf6b9cbecdc047d16990e3606173e897f96e92359dbe933c252063ab77.mp4
seru@titan:/home/streama/data/upload$
```

**Comment by dularion** [comment]
Since you had a playback error also, does that mean some files worked? in that case, is this one specific file?

**Comment by Serubin** [comment]
This is several files not working. I've had to upload things multiple times to get them up though.
I've managed to get about 5 movies up, however that's with 1-3 upload attempts each

**Comment by dularion** [comment]
hmmmm ... this is getting quite mysterious. Can we PM somehow? skype?

**Comment by Serubin** [comment]
Yes - skype should work, It should be serubin323 in the boston mass us area

**Comment by dularion** [comment]
Please reopen if the error persists.
