### ISSUE TITLE
Editing user roles and trying to save results in "Error trying to save the user"

### ISSUE THREAD

**Issue by Duckbuster** [dularion/streama#563]
### Issue description
Fresh install of Streama 1.5.1 using MySQL (MariaDB) database.
Editing a user and enabling or disabling roles, produces a "Error trying to save the user" when trying to save.

### Expected Behaviour

It should be saved

### Actual Behaviour

The error "Error trying to save the user" pops up and server has this stack trace:
```

ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] - Exception Processing ErrorPage[errorCode=0, location=/error]
 java.lang.IllegalStateException: There was a problem retrieving the current GrailsWebRequest. This usually indicates a filter ordering issue (the 'springSecurityFilterChain' filter-mapping element must be positioned after the 'grailsWebRequest' element when using @S
         at grails.plugin.springsecurity.web.access.intercept.AnnotationFilterInvocationDefinition.determineUrl(AnnotationFilterInvocationDefinition.groovy:90)
         at grails.plugin.springsecurity.web.access.intercept.AbstractFilterInvocationDefinition.getAttributes(AbstractFilterInvocationDefinition.groovy:72)
         at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:197)
         at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:124)
         at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
         at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
         at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:53)
         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
         at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
         at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
         at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
         at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62)
         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
         at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
         at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
         at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
         at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
         at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:726)
         at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:471)
         at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:394)
         at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:311)
         at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:395)
         at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:254)
         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:177)
         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
         at java.lang.Thread.run(Thread.java:748)

```

### Environment Information

- **Operating System**: Debian 9 
- **Streama version**: 1.5.1

**Comment by dularion** [comment]
Thanks for reporting this. I didnt quite fix the issue itself, but i fixed that the error message only outputs "Error trying to save the user" because the stacktrace you are showing is actually unrelated. 
So in the new v1.5.2 release you will be able to at least see whats wrong and can report back

**Comment by dularion** [comment]
please try with this release: https://github.com/dularion/streama/releases/tag/v1.5.2

**Comment by Duckbuster** [comment]
I updated and used build 1.5.2 and no error pops up anymore, and it seems to work now.
I didn't touch my streama instance since then, all I did was replace the war and restart it.  
Strange...

**Comment by dularion** [comment]
haha oh well! then thats good news then :)

**Comment by dularion** [comment]
If the problem reappears let me know!
