### ISSUE TITLE
You do not have the rights to carry out this action v2

### ISSUE THREAD

**Issue by manhast** [dularion/streama#580]
hello everyone, I put the streama in tomcat in a java hosting, it's running but there's this error when I go to the dashboard or if I create a movie / tv series.

attached screen

this is dashboard errors:

```
Error: [$compile:tpload] Failed to load template: bootstrap/match-multiple.tpl.html (HTTP status: 403 Forbidden)
http://errors.angularjs.org/1.4.12/$compile/tpload?p0=bootstrap%2Fmatch-multiple.tpl.html&p1=403&p2=Forbidden
   at Anonymous function (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:430:224)
   at Anonymous function (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:403:59)
   at r.prototype.$eval (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:418:36)
   at r.prototype.$digest (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:415:40)
   at r.prototype.$apply (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:418:339)
   at e (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d
Error: [$compile:tpload] Failed to load template: bootstrap/choices.tpl.html (HTTP status: 403 Forbidden)
http://errors.angularjs.org/1.4.12/$compile/tpload?p0=bootstrap%2Fchoices.tpl.html&p1=403&p2=Forbidden
   at Anonymous function (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:430:224)
   at Anonymous function (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:403:59)
   at r.prototype.$eval (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:418:36)
   at r.prototype.$digest (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:415:40)
   at r.prototype.$apply (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:418:339)
   at e (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9
Error: [$compile:tpload] Failed to load template: bootstrap/select-multiple.tpl.html (HTTP status: 403 Forbidden)
http://errors.angularjs.org/1.4.12/$compile/tpload?p0=bootstrap%2Fselect-multiple.tpl.html&p1=403&p2=Forbidden
   at Anonymous function (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:430:224)
   at Anonymous function (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:403:59)
   at r.prototype.$eval (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:418:36)
   at r.prototype.$digest (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:415:40)
   at r.prototype.$apply (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:418:339)
   at e (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b1
Error: [$compile:tpload] Failed to load template: uib/template/typeahead/typeahead-popup.html (HTTP status: 403 Forbidden)
http://errors.angularjs.org/1.4.12/$compile/tpload?p0=uib%2Ftemplate%2Ftypeahead%2Ftypeahead-popup.html&p1=403&p2=Forbidden
   at Anonymous function (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:430:224)
   at Anonymous function (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:403:59)
   at r.prototype.$eval (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:418:36)
   at r.prototype.$digest (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:415:40)
   at r.prototype.$apply (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:418:339)
   at e (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/asse

```
![errore](https://user-images.githubusercontent.com/12811470/37165161-d9efde52-22f3-11e8-9930-2e4c2b512b83.PNG)

and this when I click a new movie:

```
Error: [$compile:tpload] Failed to load template: uib/template/modal/window.html (HTTP status: 403 Forbidden)
http://errors.angularjs.org/1.4.12/$compile/tpload?p0=uib%2Ftemplate%2Fmodal%2Fwindow.html&p1=403&p2=Forbidden
   at Anonymous function (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:430:224)
   at Anonymous function (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:403:59)
   at r.prototype.$eval (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:418:36)
   at r.prototype.$digest (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:415:40)
   at r.prototype.$apply (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d4088b0c23a39a9edd3.js:418:339)
   at e (http://jpcloudeu004.nshostserver.net:33646/streama-1.5.2/assets/vendor-5748a59930b10d40


```

**Comment by Jeronimo95** [comment]
I'm not quite sure what the cause of this is. Looks like the server is responding with a 403 error when loading the templates. Just to be clear you're running the .war on a tomcat server (rather than with the one embedded in the .war)? Does the issue occur if you run the .war directly? What do the server side logs say?

**Comment by manhast** [comment]
yes, it's in the tomcat system, to test ... I just solved:

I replaced the folder streama to that of ROOT, in practice I renamed the real ROOT in ROOT-2, then that streama.war rename it in ROOT.war then with automatic undeploy a ROOT folder appears and runs directly.

I think the problem is the url or the path, being not very experienced in this field, I opted for this drastic solution.
