### ISSUE TITLE
./grailsw run-war error 

### ISSUE THREAD

**Issue by NickWinston123** [dularion/streama#6]
root@Anthony:~/Downloads/streama-master# ./grailsw run-war --stacktrace
Jul 30, 2015 10:53:10 AM org.codehaus.groovy.runtime.m12n.MetaInfExtensionModule newModule
WARNING: Module [groovy-all] - Unable to load extension class [org.codehaus.groo| Precompiling Assets!.
| Error Error executing script RunWar: java/nio/file/FileSystems (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.lang.NoClassDefFoundError: java/nio/file/FileSystems
	at asset.pipeline.fs.AbstractAssetResolver.isFileMatchingPatterns(AbstractAssetResolver.groovy:214)
	at asset.pipeline.fs.FileSystemAssetResolver$_iterateOverFileSystem_closure4.doCall(FileSystemAssetResolver.groovy:195)
	at asset.pipeline.fs.FileSystemAssetResolver.iterateOverFileSystem(FileSystemAssetResolver.groovy:191)
	at asset.pipeline.fs.FileSystemAssetResolver$_iterateOverFileSystem_closure4.doCall(FileSystemAssetResolver.groovy:194)
	at asset.pipeline.fs.FileSystemAssetResolver.iterateOverFileSystem(FileSystemAssetResolver.groovy:191)
	at asset.pipeline.fs.FileSystemAssetResolver.scanForFiles(FileSystemAssetResolver.groovy:180)
	at asset.pipeline.fs.FileSystemAssetResolver.scanForFiles(FileSystemAssetResolver.groovy:183)
	at asset.pipeline.fs.AssetResolver$scanForFiles.call(Unknown Source)
	at asset.pipeline.AssetCompiler$_getAllAssets_closure3.doCall(AssetCompiler.groovy:231)
	at asset.pipeline.AssetCompiler.getAllAssets(AssetCompiler.groovy:230)
	at asset.pipeline.AssetCompiler$getAllAssets$1.callCurrent(Unknown Source)
	at asset.pipeline.AssetCompiler.compile(AssetCompiler.groovy:65)
	at asset.pipeline.AssetCompiler$compile.call(Unknown Source)
	at _AssetCompile_groovy$_run_closure2.doCall(_AssetCompile_groovy:78)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at _Events$_run_closure1.doCall(_Events.groovy:5)
	at _GrailsWar$_run_closure2.doCall(_GrailsWar.groovy:43)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at RunWar$_run_closure1.doCall(RunWar.groovy:40)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:381)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy:415)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy)
	at gant.Gant.withBuildListeners(Gant.groovy:427)
	at gant.Gant.this$2$withBuildListeners(Gant.groovy)
	at gant.Gant$this$2$withBuildListeners$0.callCurrent(Unknown Source)
	at gant.Gant.dispatch(Gant.groovy:415)
	at gant.Gant.this$2$dispatch(Gant.groovy)
	at gant.Gant.invokeMethod(Gant.groovy)
	at gant.Gant.executeTargets(Gant.groovy:591)
	at gant.Gant.executeTargets(Gant.groovy:590)
	at org.grails.wrapper.GrailsWrapper.main(GrailsWrapper.java:93)
Caused by: java.lang.ClassNotFoundException: java.nio.file.FileSystems
	... 51 more
| Error Error executing script RunWar: java/nio/file/FileSystems

is there something wrong with my version of java?

root@Anthony:~# java -version
java version "1.6.0_35"
OpenJDK Runtime Environment (IcedTea6 1.13.7) (6b35-1.13.7-1~deb7u1)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)

**Comment by dularion** [comment]
Yea, 1.6 is a bit on the old side. It uses the one that is set in your JAVA_HOME Variable. You should try to go for the latest stable jdk1.7.x. I use 1.8.0_40 actually, but that is not required.

**Comment by ethanmay** [comment]
Hi @dularion,

I'm getting the same error on my end. I had the same JDK version as @NickWinston123, just updated to  v1.8.0_51. The same error occurs. I'm running OSX Yosemite for my OS.

**Comment by dularion** [comment]
Actually, I made a mistake .. I don't run it in 1.8.0_40.. i run it with 1.7.0_65. Seems like my IDE had a special setting that overrode my java version. Btw, I'm also running on OS X Yosemite. I'm sorry for the trouble and the wrong info. Would be so kind to try with 1.7.x and let me know if it worked?

**Comment by ethanmay** [comment]
Aha! Downloaded and installed v1.7.0_79 and it's precompiling like a charm!

**Comment by dularion** [comment]
Great! And sorry again for the info :P

**Comment by Faridmurzone** [comment]
Exactly the same for me. Didn't work with 1.8.0_91, and worked perfect with 1.7.0_80. Thanks @dularion
